
private _unitType = typeOf player;

{	player removeWeapon _x;	} forEach (weapons player);
removeHeadgear player;
removeVest player;
removeBackpack player;
removeUniform player;

private _radioItem = "ItemRadio";
if (isClass (configFile >> "CfgPatches" >> "task_force_radio")) then {
    _radioItem = "TFAR_anprc152";
};

switch (_unitType) do {
	
	case "B_recon_TL_F";
	case "B_recon_JTAC_F";
	case "B_Soldier_SL_F": {player setUnitLoadout [["arifle_MX_GL_Black_F","","acc_pointer_IR","optic_Hamr",["30Rnd_65x39_caseless_black_mag",30],[],""],[],[],["U_B_CombatUniform_mcam",[["FirstAidKit",2],["SmokeShellBlue",2,1],["HandGrenade",1,1],["Laserbatteries",1,1]]],["V_PlateCarrier2_rgr",[["30Rnd_65x39_caseless_black_mag",4,30],["30Rnd_65x39_caseless_black_mag_Tracer",1,30],["1Rnd_HE_Grenade_shell",3,1],["1Rnd_SmokeBlue_Grenade_shell",3,1],["1Rnd_SmokeOrange_Grenade_shell",2,1],["1Rnd_SmokePurple_Grenade_shell",2,1],["1Rnd_SmokeYellow_Grenade_shell",2,1],["1Rnd_SmokeGreen_Grenade_shell",2,1],["1Rnd_Smoke_Grenade_shell",2,1]]],[],"H_HelmetB","",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS",_radioItem,"ItemCompass","ItemWatch","NVGoggles"]]};
	case "B_recon_medic_F";
	case "B_medic_F": {player setUnitLoadout [["arifle_MX_Black_F","","","optic_Hamr",["30Rnd_65x39_caseless_black_mag",30],[],""],[],[],["U_B_CombatUniform_mcam",[["FirstAidKit",2],["SmokeShellBlue",2,1],["HandGrenade",1,1]]],["V_PlateCarrier2_rgr",[["30Rnd_65x39_caseless_black_mag",4,30],["30Rnd_65x39_caseless_black_mag_Tracer",1,30],["SmokeShellBlue",2,1]]],["B_TacticalPack_rgr",[["Medikit",1],["FirstAidKit",20]]],"H_HelmetSpecB","",[],["ItemMap","ItemGPS",_radioItem,"ItemCompass","ItemWatch","NVGoggles"]]};
	case "B_soldier_repair_F": {player setUnitLoadout [["arifle_MX_Black_F","","","optic_Hamr",["30Rnd_65x39_caseless_black_mag",30],[],""],[],[],["U_B_CombatUniform_mcam",[["FirstAidKit",2],["HandGrenade",1,1],["SmokeShellBlue",2,1]]],["V_PlateCarrier2_rgr",[["30Rnd_65x39_caseless_black_mag",4,30],["30Rnd_65x39_caseless_black_mag_Tracer",1,30]]],["B_AssaultPack_rgr",[["ToolKit",1]]],"H_HelmetB","",[],["ItemMap","",_radioItem,"ItemCompass","ItemWatch","NVGoggles"]]};
	case "B_soldier_AR_F": {player setUnitLoadout [["LMG_Mk200_F","","","optic_Hamr",["200Rnd_65x39_cased_Box",200],[],"bipod_01_F_blk"],[],[],["U_B_CombatUniform_mcam",[["FirstAidKit",2],["HandGrenade",1,1],["SmokeShellBlue",2,1]]],["V_PlateCarrier2_rgr",[["200Rnd_65x39_cased_Box",2,200]]],["B_AssaultPack_rgr",[["200Rnd_65x39_cased_Box",2,200]]],"H_HelmetB","",["Binocular","","","",[],[],""],["ItemMap","",_radioItem,"ItemCompass","ItemWatch","NVGoggles"]] };
	case "B_Soldier_GL_F": {player setUnitLoadout [["arifle_MX_GL_Black_F","","acc_pointer_IR","optic_Hamr",["30Rnd_65x39_caseless_black_mag",30],[],""],[],[],["U_B_CombatUniform_mcam",[["FirstAidKit",2],["SmokeShellBlue",2,1],["HandGrenade",1,1],["Laserbatteries",1,1]]],["V_PlateCarrier2_rgr",[["30Rnd_65x39_caseless_black_mag",4,30],["30Rnd_65x39_caseless_black_mag_Tracer",1,30],["1Rnd_HE_Grenade_shell",3,1],["1Rnd_SmokeBlue_Grenade_shell",3,1],["1Rnd_SmokeOrange_Grenade_shell",2,1],["1Rnd_SmokePurple_Grenade_shell",2,1],["1Rnd_SmokeYellow_Grenade_shell",2,1],["1Rnd_SmokeGreen_Grenade_shell",2,1],["1Rnd_Smoke_Grenade_shell",2,1]]],[],"H_HelmetB","",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS",_radioItem,"ItemCompass","ItemWatch","NVGoggles"]]};
	case "B_recon_M_F";
	case "B_soldier_M_F": {player setUnitLoadout [["srifle_EBR_F","","acc_pointer_IR","optic_DMS",[],[],"bipod_01_F_blk"],[],[],["U_B_CombatUniform_mcam",[["FirstAidKit",2],["HandGrenade",1,1],["SmokeShellBlue",2,1],["Laserbatteries",1,1]]],["V_PlateCarrier2_rgr",[["20Rnd_762x51_Mag",6,20]]],[],"H_HelmetB_camo","G_Bandanna_tan",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","",_radioItem,"ItemCompass","ItemWatch","NVGoggles"]] };
	case "B_recon_LAT_F";
	case "B_soldier_AT_F": {player setUnitLoadout [["arifle_MXC_Black_F","","","optic_Hamr",["30Rnd_65x39_caseless_black_mag",30],[],""],["launch_B_Titan_short_F","","","",["Titan_AT",1],[],""],[],["U_B_CombatUniform_mcam",[["FirstAidKit",2],["HandGrenade",1,1],["SmokeShellBlue",2,1]]],["V_PlateCarrier1_rgr",[["30Rnd_65x39_caseless_black_mag",5,30]]],["B_Kitbag_rgr",[["Titan_AT",2,1],["Titan_AP",1,1]]],"H_HelmetB","",[],["ItemMap","",_radioItem,"ItemCompass","ItemWatch","NVGoggles"]] };
	case "B_soldier_LAT_F": {player setUnitLoadout [["arifle_MX_Black_F","","","optic_Hamr",["30Rnd_65x39_caseless_black_mag",30],[],""],["launch_RPG32_F","","","",["RPG32_F",1],[],""],[],["U_B_CombatUniform_mcam",[["FirstAidKit",2],["SmokeShellBlue",2,1],["HandGrenade",1,1]]],["V_PlateCarrier2_rgr",[["30Rnd_65x39_caseless_black_mag",5,30]]],["B_AssaultPack_rgr",[["RPG32_F",2,1],["RPG32_HE_F",1,1]]],"H_HelmetB","",[],["ItemMap","",_radioItem,"ItemCompass","ItemWatch","NVGoggles"]] };
	case "B_Soldier_TL_F": {player setUnitLoadout [["arifle_MX_GL_Black_F","","acc_pointer_IR","optic_Hamr",["30Rnd_65x39_caseless_black_mag",30],[],""],["launch_RPG32_F","","","",["RPG32_F",1],[],""],[],["U_B_CombatUniform_mcam",[["FirstAidKit",2],["SmokeShellBlue",2,1],["HandGrenade",1,1],["Laserbatteries",1,1]]],["V_PlateCarrier2_rgr",[["DemoCharge_Remote_Mag",2,1],["30Rnd_65x39_caseless_black_mag",5,30],["1Rnd_HE_Grenade_shell",3,1],["1Rnd_Smoke_Grenade_shell",2,1],["1Rnd_SmokeGreen_Grenade_shell",2,1],["1Rnd_SmokeBlue_Grenade_shell",2,1]]],[],"H_HelmetB","",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS",_radioItem,"ItemCompass","ItemWatch","NVGoggles"]] };
	case "B_engineer_F": {player setUnitLoadout [["arifle_MX_Black_F","","","optic_Hamr",["30Rnd_65x39_caseless_black_mag",30],[],""],[],[],["U_B_CombatUniform_mcam",[["FirstAidKit",2],["HandGrenade",1,1],["SmokeShellBlue",2,1]]],["V_PlateCarrier2_rgr",[["MineDetector",1],["30Rnd_65x39_caseless_black_mag",5,30],["ClaymoreDirectionalMine_Remote_Mag",3,1]]],["B_AssaultPack_rgr",[["ToolKit",1],["DemoCharge_Remote_Mag",4,1]]],"H_HelmetB","",[],["ItemMap","ItemGPS",_radioItem,"ItemCompass","ItemWatch","NVGoggles"]] };
	case "B_recon_exp_F";
	case "B_soldier_exp_F": {player setUnitLoadout [["arifle_MX_Black_F","","","optic_MRCO",["30Rnd_65x39_caseless_black_mag",30],[],""],[],[],["U_B_CombatUniform_mcam",[["FirstAidKit",2],["HandGrenade",1,1],["SmokeShellBlue",2,1]]],["V_PlateCarrier1_rgr",[["MineDetector",1],["30Rnd_65x39_caseless_black_mag",5,30]]],["B_Kitbag_rgr",[["ToolKit",1],["DemoCharge_Remote_Mag",4,1],["ClaymoreDirectionalMine_Remote_Mag",2,1],["APERSTripMine_Wire_Mag",2,1],["APERSBoundingMine_Range_Mag",2,1]]],"H_HelmetB","",[],["ItemMap","",_radioItem,"ItemCompass","ItemWatch","NVGoggles"]] };
	case "B_sniper_F": {player setUnitLoadout [["srifle_LRR_F","","","optic_LRPS",["7Rnd_408_Mag",7],[],""],[],[],["U_B_CombatUniform_mcam_tshirt",[["FirstAidKit",2],["SmokeShellBlue",2,1],["HandGrenade",1,1]]],["V_PlateCarrier1_rgr",[["7Rnd_408_Mag",8,7]]],[],"H_Booniehat_mcamo","",[],["ItemMap","ItemGPS",_radioItem,"ItemCompass","ItemWatch","NVGoggles"]] };
	case "B_spotter_F": {player setUnitLoadout [["arifle_MX_Black_F","","","optic_Hamr",[],[],""],[],[],["U_B_CombatUniform_mcam",[["FirstAidKit",2],["SmokeShellBlue",2,1],["HandGrenade",1,1],["Laserbatteries",1,1]]],["V_PlateCarrier2_rgr",[["30Rnd_65x39_caseless_black_mag",4,30],["30Rnd_65x39_caseless_black_mag_Tracer",1,30]]],[],"H_Booniehat_mcamo","",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS",_radioItem,"ItemCompass","ItemWatch","NVGoggles"]] };
	case "B_support_Mort_F": {player setUnitLoadout [["arifle_MXC_Black_F","","","optic_Hamr",["30Rnd_65x39_caseless_black_mag",30],[],""],[],[],["U_B_CombatUniform_mcam",[["FirstAidKit",2],["SmokeShellBlue",2,1],["HandGrenade",1,1],["Laserbatteries",1,1]]],["V_PlateCarrier1_rgr",[["30Rnd_65x39_caseless_black_mag",4,30],["30Rnd_65x39_caseless_black_mag_Tracer",1,30]]],["B_Mortar_01_weapon_F",[]],"H_Booniehat_mcamo","",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS",_radioItem,"ItemCompass","ItemWatch","NVGoggles"]] };
	case "B_soldier_UAV_F": {player setUnitLoadout [["arifle_MXC_Black_F","","","optic_Hamr",["30Rnd_65x39_caseless_black_mag",30],[],""],[],[],["U_B_CombatUniform_mcam_tshirt",[["FirstAidKit",2],["Laserbatteries",1,1],["SmokeShellBlue",2,1],["HandGrenade",1,1]]],["V_Chestrig_rgr",[["30Rnd_65x39_caseless_black_mag",4,30],["30Rnd_65x39_caseless_black_mag_Tracer",1,30]]],["B_UAV_01_backpack_F",[]],"H_Booniehat_mcamo","",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","B_UavTerminal",_radioItem,"ItemCompass","ItemWatch","NVGoggles"]] };
	case "B_Helipilot_F": {player setUnitLoadout [["SMG_03C_black","","","",["50Rnd_570x28_SMG_03",50],[],""],[],[],["U_B_HeliPilotCoveralls",[["FirstAidKit",2],["SmokeShellBlue",2,1],["HandGrenade",1,1],["Laserbatteries",1,1]]],["V_TacVest_blk",[["50Rnd_570x28_SMG_03",2,50],["SmokeShellBlue",2,1]]],[],"H_CrewHelmetHeli_B","G_Bandanna_beast",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS",_radioItem,"ItemCompass","ItemWatch","NVGoggles_OPFOR"]] };
};
